services:
  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: "neo4j/password"

volumes:
  neo4j_data:
